name: generate metrics
on:
  schedule:
    - cron: "0 * * * *" # Daily at 2 AM UTC (adjust as you see fit)
  workflow_dispatch:
  push:
    branches: ["main", "master"]

jobs:
  metrics_generation:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: generate metrics svgs
        uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          user: mythologic-al
          config_timezone: Europe/London 
          config_display: large
          config_padding: 10, 15
          config_animations: yes
          filename: github-metrics-overview.svg
          base: header, activity, community, repositories 
          plugin_introduction: yes
          plugin_introduction_title: yes
          plugin_languages: yes
          outputs_languages_filename: github-metrics-languages.svg
          plugin_languages_limit: 10
          plugin_languages_threshold: 0%
          plugin_languages_colors: github
          plugin_languages_sections: most-used
          plugin_languages_details: lines, bytes
          plugin_languages_analysis_timeout: 30
          plugin_habits: yes
          outputs_habits_filename: github-metrics-habits.svg 
          plugin_habits_from: 200
          plugin_habits_days: Sun, Mon, Tue, Wed, Thu, Fri, Sat
          plugin_habits_charts: yes
          plugin_habits_trim: yes
          plugin_habits_details: yes
          plugin_isocalendar: yes
          outputs_isocalendar_filename: github-metrics-calendar.svg 
          plugin_isocalendar_duration: full-year
          plugin_lines: yes
          outputs_lines_filename: github-metrics-lines.svg 
          plugin_lines_sections: base 
          plugin_lines_repositories_visibility: public, private
