name: Metrics
on:
  schedule: [{cron: "0 0 * * *"}]
  workflow_dispatch:
  push: {branches: ["master", "main"]} # Or your default branch
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
        contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}

          user: mythologic-al
          template: classic 
          base: header, activity, community, repositories, metadata
          config_timezone: Europe/London
          config_display: large 
          plugin_lines: yes
          plugin_lines_sections: base 
          plugin_lines_repositories_visibility: public, private
          plugin_habits: yes
          plugin_habits_from: 200 
          plugin_habits_days: Mon, Tue, Wed, Thu, Fri, Sat, Sun
          plugin_habits_charts: yes
          plugin_habits_trim: yes
          plugin_isocalendar: yes
          plugin_isocalendar_duration: full-year # Display full year instead of half year
          plugin_languages: yes
          plugin_languages_limit: 8 # Show top 8 languages
          plugin_languages_threshold: 0% # Min usage percentage
          plugin_languages_analysis_timeout: 15 # Timeout for analysis
